<!-- Pleace this snippet right after opening the head tag to make it work properly -->

<!-- This code is licensed under GNU GPL v3 -->
<!-- You are allowed to freely copy, distribute and use this code, but removing author credit is strictly prohibited -->
<!-- Generated by http://insider.zone/tools/client-side-url-redirect-generator/ -->

<!-- REDIRECTING STARTS -->
<link rel="canonical" href="http://7of9.m3u.xyz/"/>
<noscript>
    <meta http-equiv="refresh" content="0;URL=http://7of9.m3u.xyz/">
</noscript>
<!--[if lt IE 9]><script type="text/javascript">var IE_fix=true;</script><![endif]-->
<script type="text/javascript">
    var url = "http://7of9.m3u.xyz/";
    if(typeof IE_fix != "undefined") // IE8 and lower fix to pass the http referer
    {
        document.write("redirecting..."); // Don't remove this line or appendChild() will fail because it is called before document.onload to make the redirect as fast as possible. Nobody will see this text, it is only a tech fix.
        var referLink = document.createElement("a");
        referLink.href = url;
        document.body.appendChild(referLink);
        referLink.click();
    }
    else { window.location.replace(url); } // All other browsers
</script>
<!-- Credit goes to http://insider.zone/ -->
<!-- REDIRECTING ENDS -->

<dir>
<title>[COLOR aqua][B]7 of 9[/COLOR][/B] [COLOR red][B](AIO)[/COLOR] [COLORwhite]TV Shows[/COLOR][/B]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/movies/homejen.php</link>
</dir>

<item>
<title>[B][COLOR dodgerblue]**********[/COLOR][/B]</title>
</item>

<dir>
<title>[COLORdarkorange]-->[/COLOR]Authorize / Manage Real-Debrid[COLORdarkorange]<--[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/puckapks/debridmanage.xml</link>
</dir>

<dir>
  <title>Search TV IMDB</title>  
  <imdburl>searchseries</imdburl>
</dir>


  <dir>
  <title>Debrid + Free 1 Click TV Shows</title>
  <link>http://www.ezzer-mac.com/frank/ghost/ghostxmls/xmls1/alltvshows.xml</link>
  <thumbnail>http://www.ezzer-mac.com/frank/artghost/newghostfanart/series.png</thumbnail>
  <fanart>http://www.ezzer-mac.com/frank/artghost/tvshow.jpg</fanart>
  <summary>Tv Shows</summary>
  </dir> 

<dir>
<title>Trending Tv Shows</title>
<trakt>https://api.trakt.tv/shows/trending/?limit=50&page=1</trakt>
</dir>

<dir>
<title>Popular Tv Shows</title>
<trakt>https://api.trakt.tv/shows/popular/?limit=30&page=1</trakt>
</dir>
  
    <dir>
    <title>On The Air</title>
    <tmdb>tv/on_the_air</tmdb>
    <summary>Shows Airing in Next 7 Days</summary>
  </dir>

<dir>
<title>Catch-Up Tv</title>
<tvmaze>calendar</tvmaze>
</dir>


  <dir>
    <title>Top Rated</title>
    <tmdb>tv/top_rated</tmdb>
    <summary>Top Rated TMDB Shows</summary>
  </dir>
 

  <dir>
    <title>Airing Today</title>
    <tmdb>tv/today</tmdb>
    <summary>Episodes Airing Today</summary>
  </dir>
  
	 <dir>
	<title>Calender</title>
	<tvmaze>calendar</tvmaze>
	</dir> 

  
  <dir>
    <title>Genres</title>
    <link>file://shared lists/genre_tv.xml</link>
    <summary>Search Shows by Genre</summary>
  </dir>

<dir>     
<name>My Trakt</name>     
<link>http://7of9.m3u.xyz/jen/7of9-cached/mytrakt.php</link>    
</dir>  

<dir>
<title>Trakt</title>
<link>http://7of9.m3u.xyz/jen/puckapks/trakt.xml</link>
<summary>Trakt</summary>
</dir>

<item>
<title>[B][COLOR dodgerblue]**********[/COLOR][/B]</title>
</item>
 

  <dir>
    <title>Networks</title>
    <link>file://shared lists/networks.xml</link>
    <summary>Search Shows by Network</summary>
  </dir>
  
	 <dir>
		<title>Hallmark</title>
		<tvmaze>network/50/1</tvmaze>
		<fantart></fantart>
	</dir>

	<dir>
		<title>Lifetime</title>
		<tvmaze>network/18/1</tvmaze>
		<fantart></fantart>
	</dir> 

<dir>
<title>[COLORwhite]New Tv Shows[/COLOR]</title>
<imdburl>tvshows/new?limit=50&page=1</imdburl>
</dir>

<dir>
<title>[COLORwhite]On The Air in Next 7 Days[/COLOR]</title>
<tmdb>tv/on_the_air</tmdb>
<summary>Shows Airing in Next 7 Days</summary>
</dir>

<dir>
<title>[COLORwhite]TV NETWORKS[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/tvshows/networks.php</link>
<summary>Search Shows by Network</summary>
</dir>

<dir>
<title>[COLORwhite]US Networks[/COLOR]</title>
<tvmaze>country/United States/1</tvmaze>
</dir>

<dir>
<title>[COLORwhite]UK Networks[/COLOR]</title>
<tvmaze>country/United Kingdom/1</tvmaze>
</dir>

<dir>
<title>[COLORwhite]TV Show Trailers[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/tvshows/tvshows.trailers.php</link>
</dir>

<dir>
<title>[COLORwhite]IMDB: 250 Top Rated TV Shows[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/tvshows/imdbtop250tv.php</link>
</dir>

<dir>
<title>[COLORwhite]Classic Sci-Fi, Horror and Fantasy TV Shows[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/tvshows/classicscifitv.php</link>
</dir>

<dir>
<title>[COLORwhite]Classic TV Shows[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/tvshows/classictv.php</link>
</dir>

<dir>
<title>[COLORwhite]Invasion: Alien / Space[/COLOR]</title>
<tmdb>keyword/shows/14909</tmdb>
</dir>

<dir>
  <title>[COLORwhite]Reality Shows 1[/COLOR]</title>
  <tmdb>genre/shows/10764</tmdb>
</dir>

<dir>
  <title>[COLORwhite]Reality Shows 2[/COLOR]</title>
  <tmdb>list/46074</tmdb>
</dir>

<dir>
  <title>[COLORwhite]Netflix Original Series[/COLOR]</title>
  <tmdb>network/shows/213</tmdb>
</dir>

<dir>
<title>[COLORwhite]Diacovery TV[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/tvshows/discovery-tv.php</link>
</dir>

<dir>
<title>[COLORwhite]DC TV[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/tvshows/dc_tv.php</link>
</dir>

<dir>
<title>[COLORwhite]Marvel TV[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/tvshows/marvel_tv.php</link>
</dir>

<item>
<title>=======[COLOR dodgerblue]Extended Genres[/COLOR]=======</title>
</item>

<dir>
  <title>Female Protagonist</title>
  <tmdb>keyword/shows/11322</tmdb>
</dir>

<dir>
<title>Kidnapping</title>
<tmdb>keyword/shows/1930</tmdb>
</dir>

<dir>
<title>Monster(s)</title>
<tmdb>keyword/shows/1299</tmdb>
</dir>

<dir>
<title>Murder(s)</title>
<tmdb>keyword/shows/9826</tmdb>
</dir>

<dir>
<title>Serial Killer</title>
<tmdb>keyword/shows/10714</tmdb>
</dir>

<dir>
<title>Sibling Relationship</title>
<tmdb>keyword/shows/380</tmdb>
</dir>

<dir>
<title>Wife Husband Relationship</title>
<tmdb>keyword/shows/1157</tmdb>
</dir>

<dir>
<title>Space Opera</title>
<tmdb>keyword/shows/161176</tmdb>
</dir>

<dir>
<title>I Spy</title>
<tmdb>keyword/shows/470</tmdb>
</dir>

<dir>
<title>War</title>
<tmdb>keyword/shows/6091</tmdb>
</dir>

<dir>
<title>Watching The Detectives</title>
<tmdb>keyword/shows/703</tmdb>
</dir>

<dir>
<title>World's Oldest Profession</title>
<tmdb>keyword/shows/549</tmdb>
</dir>

<dir>  
<title>[COLORwhite]Pair Online Here[/COLOR]</title>
<pairwith>pairlist</pairwith>
</dir>


<dir>
<title>[COLORwhite]Settings[/COLOR]</title>
<link>http://7of9.m3u.xyz/jen/7of9-cached/settings.php</link>
</dir>